global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 25s
scrape_configs:
- job_name: 'kafka'
  static_configs:
    - targets:
      - kafka1:8081
      - kafka2:8081
      - kafka3:8081